VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "PLCol"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Enum PLCol1
    Record_Type = 1
    Enrollment_ID
    Company_Acronym
    Account_Number
    Premise_ID
    WO_Number
    Status
    Status_Date
    Status_Time
    Follow_up_Date
    Customer_contact_mode
    Comments
    Total_Conditioned_Square_Footage
    Residence_Building_Type
    Residence_Building_Class
    Year_building_constructed
    Building_occupancy_count
    First_and_last_name_of_main_auditor
    Primary_contact_name
    Primary_contact_street_address
    Primary_contact_city
    Primary_contact_state
    Primary_contact_zipcode
    Primary_contact_phone
    Primary_contact_phone_extension
    Primary_contact_email
    Primary_contact_mobile_phone
    Ownership_Type
    Service_Class
    Schedule_date
    Schedule_Time
    Number_of_Auditors
    Dog_or_Cat_Flag
    Occupancy_Frequency
    Number_of_stories_above_grade
    Air_Leakage_Rating
    Blower_door_pre_test
    Blower_door_post_test
    CFM_Reduction
    Auditor_Notes
    short_program_name
    Verification_Class
    Annual_kwh_savings
    Annual_CCF_savings
    Annual_kw_demand_savings
    Remit_to_contact_name
    Remit_to_contact_street_address
    Remit_to_contact_city
    Remit_to_contact_state
    Remit_to_contact_zipcode
    Remit_to_contact_phone
    Remit_to_contact_phone_extension
    Remit_to_contact_email
    Remit_to_contact_mobile_phone
    Mailing_Street_Address
    Mailing_City
    Mailing_State
    Mailing_Zip_Code
    XXXX_INSTALL_Percent_Savings
    Nexant_Report_Dollar_Amount_XXXX
    RECIEVED_AT_VENDOR
    Invoice_date_interfaced_XXXX
    ROSA_Installed_PCT_Savings
    ROSA_Recommended_PCT_Savings
    ROSA_Total_PCT_Savings
    HEAP_Installed_PCT_Savings
    HEAP_Total_PCT_Savings
End Enum


