VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "TRCol"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Enum TRCol1
    F_A_Status = 1
    Enrollment_Status
    Appt_Date
    Analyst
    Nexant_Project_ID
    Enrollment_ID_Duplicate
    Customer_Name
    Street_Address
    blank
    Project_ID
    Enrollment_ID
    End_Date
    Inv_Date
    Inv_Paid
    Code_Closed
    Notes1
    Status_change_date
    Notes
End Enum

